#This file analyses anonymized data provided by "loadAnonymiseSaveData.R" in exp-specific directory
#Working directory can optionally be set by Rproj file to directory that it's in, otherwise with the line below
setwd(
  "/Users/alexh/Documents/attention_tempresltn/EEGRSVP/EEG_RSVP/analysis"
)
####################analyse offCenterAndShape ################

dataDir="../dataAnonymized/"
expName="EEG_RSVP"
anonDataFilename = paste(dataDir,expName,".Rdata",sep="") #generated by loadAnonymiseSaveData.R
load(anonDataFilename,verbose=TRUE)  #returns dat
E<-dat #the data

#Sanity check SPE histogram before gathering
require(ggplot2)
#sanity check
g=ggplot(E,   aes(x=responsePosRelative0))  
g<-g+facet_grid(task~.)
g<-g+geom_histogram(bins=34)
g

#Look at percent correct for left and right
#But raw data does not give left and right explicitly - instead responsePosRelative0 and responsePosRelative1