#This file analyses anonymized data provided by "loadAnonymiseSaveData.R" in exp-specific directory
#Working directory can optionally be set by Rproj file to directory that it's in, otherwise with the line below
setwd(
  "/Users/alexh/Documents/attention_tempresltn/EEGRSVP/EEG_RSVP/analysis"
)
####################analyse offCenterAndShape ################

dataDir="../dataAnonymized/"
expName="EEG_RSVP"
anonDataFilename = paste(dataDir,expName,".Rdata",sep="") #generated by loadAnonymiseSaveData.R
load(anonDataFilename,verbose=TRUE)  #returns dat
